### ISSUE TITLE
Occasional panic when switching projects

### ISSUE THREAD

**Issue by drognisep** [drognisep/todoapp#1]
Sometimes, when the UI is left to sit for a while, switching project views will panic.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ff6b6a36318]

goroutine 5 [running]:
fyne.io/fyne/v2/widget.(*Check).Unbind(0x7ff6b679bb4a)
        C:/Users/some-user/go/pkg/mod/fyne.io/fyne/v2@v2.1.1/widget/check.go:285 +0x18
fyne.io/fyne/v2/widget.(*Check).Bind(0x0, {0x169053dade0, 0xc000c11040})
        C:/Users/some-user/go/pkg/mod/fyne.io/fyne/v2@v2.1.1/widget/check.go:119 +0x31
todo/view.(*TaskView).update(0xc0004b5ea0, 0xc00009d1a0, 0xc000c71650)
        C:/Users/some-user/git/todoapp/view/task.go:38 +0x136
todo/view.NewTaskList.func3(0x0, {0x7ff6b6f4f9a8, 0xc0004b5ea0})
        C:/Users/some-user/git/todoapp/view/tasklist.go:32 +0xaa
fyne.io/fyne/v2/widget.(*listLayout).setupListItem(0xc00012c0a0, 0xc0004b5f10, 0x0)
        C:/Users/some-user/go/pkg/mod/fyne.io/fyne/v2@v2.1.1/widget/list.go:411 +0x9b
fyne.io/fyne/v2/widget.(*listLayout).updateList(0xc00012c0a0, 0x1)
        C:/Users/some-user/go/pkg/mod/fyne.io/fyne/v2@v2.1.1/widget/list.go:456 +0x418
fyne.io/fyne/v2/widget.(*List).Resize(0xc00041c1c0, {0xb6793c09, 0x7ff6})
        C:/Users/some-user/go/pkg/mod/fyne.io/fyne/v2@v2.1.1/widget/list.go:114 +0x66
fyne.io/fyne/v2/layout.(*maxLayout).Layout(0xc001287e28, {0xc00055e0c0, 0x1, 0x7ff6b68daac4}, {0x0, 0x0})
        C:/Users/some-user/go/pkg/mod/fyne.io/fyne/v2@v2.1.1/layout/maxlayout.go:22 +0x82
fyne.io/fyne/v2.(*Container).layout(...)
        C:/Users/some-user/go/pkg/mod/fyne.io/fyne/v2@v2.1.1/container.go:168
fyne.io/fyne/v2.(*Container).Add(0xc00055e0c0, {0x7ff6b6f4f8e8, 0xc00041c1c0})
        C:/Users/some-user/go/pkg/mod/fyne.io/fyne/v2@v2.1.1/container.go:57 +0xe5
github.com/drognisep/fynehelpers/layouthelp.(*MultiView).push(0xc00007a1e0, {0x7ff6b6f4f8e8, 0xc00041c1c0})
        C:/Users/some-user/go/pkg/mod/github.com/drognisep/fynehelpers@v0.0.0-20211118062401-49513fc7476f/layouthelp/multiview.go:40 +0xec
github.com/drognisep/fynehelpers/layouthelp.(*MultiView).Replace(0xc00007a1e0, {0x7ff6b6f4f8e8, 0xc00041c1c0})
        C:/Users/some-user/go/pkg/mod/github.com/drognisep/fynehelpers@v0.0.0-20211118062401-49513fc7476f/layouthelp/multiview.go:83 +0xd1
todo/view.(*TaskListSelector).onChanged(0xc00041c000, {0xc0003803c0, 0xc001287ef8})
        C:/Users/some-user/git/todoapp/view/taskListSelector.go:78 +0x193
fyne.io/fyne/v2/widget.(*Select).updateSelected(0xc00041c000, {0xc0003803c0, 0xc00007a0b8})
        C:/Users/some-user/go/pkg/mod/fyne.io/fyne/v2@v2.1.1/widget/select.go:261 +0x55
fyne.io/fyne/v2/widget.(*Select).showPopUp.func1()
        C:/Users/some-user/go/pkg/mod/fyne.io/fyne/v2@v2.1.1/widget/select.go:237 +0x2a
fyne.io/fyne/v2/widget.(*menuItem).trigger(0xc00136d620)
        C:/Users/some-user/go/pkg/mod/fyne.io/fyne/v2@v2.1.1/widget/menu_item.go:163 +0x3c
fyne.io/fyne/v2/widget.(*menuItem).Tapped(0xc001287fb0, 0xc00040c001)
        C:/Users/some-user/go/pkg/mod/fyne.io/fyne/v2@v2.1.1/widget/menu_item.go:109 +0x58
fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseClickedHandleTapDoubleTap.func1()
        C:/Users/some-user/go/pkg/mod/fyne.io/fyne/v2@v2.1.1/internal/driver/glfw/window.go:891 +0x26
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0xc00040c000)
        C:/Users/some-user/go/pkg/mod/fyne.io/fyne/v2@v2.1.1/internal/driver/common/window.go:58 +0x56
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        C:/Users/some-user/go/pkg/mod/fyne.io/fyne/v2@v2.1.1/internal/driver/glfw/window.go:1395 +0x15b
```

**Comment by drognisep** [comment]
Resolved with a change in the task view renderer.
